"""
Tests for app.core.query_planner.QueryPlanner.

These tests use a mocked BedrockClient, so they do not require:
- AWS credentials
- Bedrock access
- network access
- Streamlit
- DuckDB

The planner is tested as an isolated transformation:

DatasetProfile + natural-language question
                ↓
          mocked LLM response
                ↓
             SQL
"""

from unittest.mock import MagicMock

import pytest

from app.core.query_planner import (
    DEFAULT_SYSTEM_PROMPT,
    EmptyQuestionError,
    QueryPlanner,
    QueryPlanningError,
)
from app.models.schemas import (
    ColumnProfile,
    DatasetProfile,
)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _dataset_profile() -> DatasetProfile:
    """Return a small realistic dataset profile for planner tests."""
    return DatasetProfile(
        row_count=100,
        column_count=4,
        columns=[
            ColumnProfile(
                name="city",
                pandas_dtype="object",
                inferred_type="string",
                null_count=0,
                null_percentage=0.0,
                unique_count=5,
            ),
            ColumnProfile(
                name="category",
                pandas_dtype="object",
                inferred_type="string",
                null_count=2,
                null_percentage=2.0,
                unique_count=3,
            ),
            ColumnProfile(
                name="revenue",
                pandas_dtype="float64",
                inferred_type="float",
                null_count=1,
                null_percentage=1.0,
                unique_count=90,
                min=10.5,
                max=9999.99,
                mean=1250.75,
            ),
            ColumnProfile(
                name="orders",
                pandas_dtype="int64",
                inferred_type="integer",
                null_count=0,
                null_percentage=0.0,
                unique_count=50,
                min=1,
                max=500,
                mean=100.0,
            ),
        ],
        sample_rows=[
            {
                "city": "Kolkata",
                "category": "Food",
                "revenue": 1200.50,
                "orders": 10,
            },
            {
                "city": "Delhi",
                "category": "Grocery",
                "revenue": 900.00,
                "orders": 7,
            },
        ],
    )


def _mock_llm(response: str) -> MagicMock:
    """Create a mocked Bedrock client returning the supplied response."""
    client = MagicMock()
    client.generate_text.return_value = response
    return client


# --------------------------------------------------------------------------
# Successful planning
# --------------------------------------------------------------------------


def test_plan_generates_sql_from_question():
    """Planner should return SQL generated by the LLM."""
    llm = _mock_llm(
        "SELECT city, SUM(revenue) AS total_revenue "
        "FROM dataset "
        "GROUP BY city "
        "ORDER BY total_revenue DESC "
        "LIMIT 5"
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "What are the top 5 cities by revenue?",
        _dataset_profile(),
    )

    assert result == (
        "SELECT city, SUM(revenue) AS total_revenue "
        "FROM dataset "
        "GROUP BY city "
        "ORDER BY total_revenue DESC "
        "LIMIT 5"
    )


def test_plan_calls_llm_once():
    """One planning request should result in exactly one LLM call."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "How many records are there?",
        _dataset_profile(),
    )

    llm.generate_text.assert_called_once()


def test_plan_uses_zero_temperature():
    """SQL generation should be deterministic by default."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs

    assert kwargs["temperature"] == 0.0
    assert kwargs["max_tokens"] == 1024


def test_plan_uses_system_prompt():
    """Planner should send its system prompt to the LLM."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs

    assert kwargs["system_prompt"] == DEFAULT_SYSTEM_PROMPT


def test_plan_accepts_custom_system_prompt():
    """A custom system prompt should override the default."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    custom_prompt = "You are a strict DuckDB SQL expert."

    planner = QueryPlanner(
        llm_client=llm,
        system_prompt=custom_prompt,
    )

    planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs

    assert kwargs["system_prompt"] == custom_prompt


# --------------------------------------------------------------------------
# Prompt construction
# --------------------------------------------------------------------------


def test_prompt_contains_user_question():
    """The user's question must be included in the LLM prompt."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    question = "What is the total revenue?"

    planner.plan(
        question,
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs
    prompt = kwargs["prompt"]

    assert question in prompt


def test_prompt_contains_dataset_column_names():
    """The prompt must expose available dataset columns to the LLM."""
    llm = _mock_llm("SELECT SUM(revenue) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "What is total revenue?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs
    prompt = kwargs["prompt"]

    assert '"city"' in prompt
    assert '"category"' in prompt
    assert '"revenue"' in prompt
    assert '"orders"' in prompt


def test_prompt_contains_dataset_statistics():
    """Useful numeric profile information should reach the LLM."""
    llm = _mock_llm("SELECT AVG(revenue) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "What is the average revenue?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs
    prompt = kwargs["prompt"]

    assert "9999.99" in prompt
    assert "1250.75" in prompt


def test_prompt_tells_llm_to_use_dataset_table():
    """The prompt should establish the table name expected by execution."""
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    planner.plan(
        "How many records are there?",
        _dataset_profile(),
    )

    kwargs = llm.generate_text.call_args.kwargs
    prompt = kwargs["prompt"]

    assert "`dataset`" in prompt


# --------------------------------------------------------------------------
# Question validation
# --------------------------------------------------------------------------


def test_plan_rejects_empty_question():
    """An empty question should fail before calling the LLM."""
    llm = _mock_llm("SELECT 1")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(EmptyQuestionError):
        planner.plan("", _dataset_profile())

    llm.generate_text.assert_not_called()


def test_plan_rejects_whitespace_question():
    """Whitespace-only questions should fail before calling the LLM."""
    llm = _mock_llm("SELECT 1")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(EmptyQuestionError):
        planner.plan("   \n\t  ", _dataset_profile())

    llm.generate_text.assert_not_called()


def test_plan_rejects_non_string_question():
    """A non-string question should fail cleanly."""
    llm = _mock_llm("SELECT 1")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(EmptyQuestionError):
        planner.plan(None, _dataset_profile())

    llm.generate_text.assert_not_called()


# --------------------------------------------------------------------------
# DatasetProfile validation
# --------------------------------------------------------------------------


def test_plan_rejects_invalid_dataset_profile():
    """Planner should require a real DatasetProfile."""
    llm = _mock_llm("SELECT 1")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(ValueError):
        planner.plan(
            "How many rows are there?",
            {"row_count": 10},
        )

    llm.generate_text.assert_not_called()


# --------------------------------------------------------------------------
# SQL extraction / normalization
# --------------------------------------------------------------------------


def test_extracts_sql_from_markdown_sql_fence():
    """Planner should tolerate ```sql ... ``` responses."""
    llm = _mock_llm(
        """```sql
SELECT city, SUM(revenue) AS total_revenue
FROM dataset
GROUP BY city
```"""
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "Show revenue by city.",
        _dataset_profile(),
    )

    assert result == (
        "SELECT city, SUM(revenue) AS total_revenue\n"
        "FROM dataset\n"
        "GROUP BY city"
    )


def test_extracts_sql_from_generic_markdown_fence():
    """Planner should also tolerate a generic ``` ... ``` fence."""
    llm = _mock_llm(
        """```
SELECT COUNT(*) FROM dataset
```"""
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    assert result == "SELECT COUNT(*) FROM dataset"


def test_removes_trailing_semicolon():
    """A single trailing semicolon should be normalized away."""
    llm = _mock_llm(
        "SELECT COUNT(*) FROM dataset;"
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    assert result == "SELECT COUNT(*) FROM dataset"


def test_accepts_lowercase_select():
    """SQL keywords do not need to be uppercase."""
    llm = _mock_llm(
        "select count(*) from dataset"
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    assert result == "select count(*) from dataset"


def test_accepts_leading_whitespace():
    """Leading/trailing whitespace should be normalized."""
    llm = _mock_llm(
        "   SELECT COUNT(*) FROM dataset   "
    )

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    assert result == "SELECT COUNT(*) FROM dataset"


# --------------------------------------------------------------------------
# Invalid LLM responses
# --------------------------------------------------------------------------


def test_rejects_empty_llm_response():
    """An empty LLM response should become QueryPlanningError."""
    llm = _mock_llm("")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "How many rows are there?",
            _dataset_profile(),
        )


def test_rejects_whitespace_llm_response():
    """Whitespace-only LLM responses should be rejected."""
    llm = _mock_llm("   \n\t ")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "How many rows are there?",
            _dataset_profile(),
        )


def test_rejects_non_select_response():
    """Planner should reject responses that don't start with SELECT."""
    llm = _mock_llm(
        "DELETE FROM dataset"
    )

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "Delete everything.",
            _dataset_profile(),
        )


def test_rejects_explanation_before_sql():
    """Plain explanatory text before SQL should not be accepted."""
    llm = _mock_llm(
        "Here is the SQL:\nSELECT COUNT(*) FROM dataset"
    )

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "How many rows are there?",
            _dataset_profile(),
        )


def test_rejects_multiple_sql_statements():
    """Planner should reject multiple statements."""
    llm = _mock_llm(
        "SELECT COUNT(*) FROM dataset; SELECT SUM(revenue) FROM dataset"
    )

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "Give me multiple results.",
            _dataset_profile(),
        )


def test_rejects_select_followed_by_second_statement():
    """A second statement after a SELECT must not pass through."""
    llm = _mock_llm(
        "SELECT COUNT(*) FROM dataset; DROP TABLE dataset"
    )

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(QueryPlanningError):
        planner.plan(
            "Count the records.",
            _dataset_profile(),
        )


# --------------------------------------------------------------------------
# LLM error propagation
# --------------------------------------------------------------------------


def test_llm_client_error_is_not_silently_swallowed():
    """
    BedrockClient errors should propagate rather than being disguised as
    successful SQL generation.
    """
    llm = MagicMock()
    llm.generate_text.side_effect = RuntimeError("Bedrock unavailable")

    planner = QueryPlanner(llm_client=llm)

    with pytest.raises(RuntimeError, match="Bedrock unavailable"):
        planner.plan(
            "How many rows are there?",
            _dataset_profile(),
        )


# --------------------------------------------------------------------------
# Architecture boundary
# --------------------------------------------------------------------------


def test_query_planner_does_not_execute_sql():
    """
    QueryPlanner should only call the LLM.

    SQL execution belongs to SQLExecutor and must not happen inside the
    planner.
    """
    llm = _mock_llm("SELECT COUNT(*) FROM dataset")

    planner = QueryPlanner(llm_client=llm)

    result = planner.plan(
        "How many rows are there?",
        _dataset_profile(),
    )

    assert result == "SELECT COUNT(*) FROM dataset"

    # The only dependency interaction in this test is the LLM call.
    llm.generate_text.assert_called_once()


# --------------------------------------------------------------------------
# Static extraction helper
# --------------------------------------------------------------------------


def test_extract_sql_directly():
    """The internal SQL extraction helper should normalize valid SQL."""
    result = QueryPlanner._extract_sql(
        "```sql\nSELECT * FROM dataset;\n```"
    )

    assert result == "SELECT * FROM dataset"


def test_extract_sql_rejects_empty_string():
    """Direct SQL extraction should reject an empty response."""
    with pytest.raises(QueryPlanningError):
        QueryPlanner._extract_sql("")


def test_extract_sql_rejects_non_select():
    """Direct SQL extraction should reject non-SELECT statements."""
    with pytest.raises(QueryPlanningError):
        QueryPlanner._extract_sql("UPDATE dataset SET revenue = 0")


def test_extract_sql_rejects_multiple_statements():
    """Direct SQL extraction should reject multiple statements."""
    with pytest.raises(QueryPlanningError):
        QueryPlanner._extract_sql(
            "SELECT * FROM dataset; SELECT COUNT(*) FROM dataset"
        )