"""
Main orchestration layer for the AI Data Analyst Agent.

Pipeline:

    User Question
          |
          v
    QueryPlanner
          |
          v
    SQL Security Validation
          |
          v
    SQLExecutor
          |
          v
    QueryResult
       /           \
      v             v
  Explainer  Chart Generator

This module coordinates the pipeline but deliberately keeps each
responsibility inside its own component.

Agent does NOT:
- execute raw/unvalidated SQL,
- communicate directly with AWS/Bedrock,
- render Streamlit UI,
- contain SQL security rules,
- generate SQL itself.

Those responsibilities belong to:
- QueryPlanner
- validate_sql()
- SQLExecutor
- Explainer
- Chart Generator
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Dict, Optional

import pandas as pd

from app.core.chart_generator import generate_chart
from app.config import config
from app.core.explainer import ExplainerError, explain_query_result
from app.core.query_planner import QueryPlanner, QueryPlannerError
from app.core.sql_executor import (
    DEFAULT_TABLE_NAME,
    QueryExecutionError,
    QueryTimeoutError,
    SQLExecutor,
    UnvalidatedSQLError,
)
from app.models.schemas import DatasetProfile, QueryResult, ValidationResult
from app.utils.logger import get_logger
from app.utils.security import validate_sql


logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class AgentError(Exception):
    """Base class for errors raised by the AI Data Analyst Agent."""


class AgentValidationError(AgentError):
    """Raised when generated SQL fails security validation."""


class AgentPlanningError(AgentError):
    """Raised when SQL generation/planning fails."""


class AgentExecutionError(AgentError):
    """Raised when validated SQL execution fails."""


class AgentExplanationError(AgentError):
    """Raised when explanation generation fails."""


class AgentChartError(AgentError):
    """Raised when chart generation fails."""


# ---------------------------------------------------------------------------
# Result contract
# ---------------------------------------------------------------------------


@dataclass
class AgentResult:
    """
    Complete result produced by one agent run.

    Attributes
    ----------
    question:
        Original user question.

    sql:
        SQL generated by QueryPlanner.

    validation:
        ValidationResult returned by the security layer.

    query_result:
        Data returned by SQLExecutor.

    explanation:
        Optional natural-language explanation.

    chart:
        Optional chart specification.
    """

    question: str
    sql: str
    validation: ValidationResult
    query_result: QueryResult
    explanation: Optional[str] = None
    chart: Optional[Dict[str, Any]] = None


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------


DEFAULT_MAX_RESULT_ROWS = config.max_query_result_rows
DEFAULT_MAX_EXPLANATION_ROWS = 20
DEFAULT_MAX_CHART_ROWS = 20
DEFAULT_MAX_CATEGORIES = 20


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------


class DataAnalystAgent:
    """
    Orchestrates the complete AI Data Analyst pipeline.

    The agent accepts:
        - a pandas DataFrame,
        - its DatasetProfile,
        - and a natural-language analytical question.

    It then:

        1. Generates SQL using QueryPlanner.
        2. Validates the SQL using validate_sql().
        3. Executes only validated SQL using SQLExecutor.
        4. Generates an explanation.
        5. Generates an optional chart specification.
    """

    def __init__(
        self,
        dataframe: pd.DataFrame,
        dataset_profile: DatasetProfile,
        query_planner: Optional[QueryPlanner] = None,
        max_result_rows: int = DEFAULT_MAX_RESULT_ROWS,
        max_explanation_rows: int = DEFAULT_MAX_EXPLANATION_ROWS,
        max_chart_rows: int = DEFAULT_MAX_CHART_ROWS,
        max_categories: int = DEFAULT_MAX_CATEGORIES,
    ) -> None:
        if not isinstance(dataframe, pd.DataFrame):
            raise ValueError(
                "dataframe must be a pandas DataFrame"
            )

        if not isinstance(dataset_profile, DatasetProfile):
            raise ValueError(
                "dataset_profile must be a DatasetProfile"
            )

        if max_result_rows <= 0:
            raise ValueError(
                "max_result_rows must be greater than 0"
            )

        if max_explanation_rows < 0:
            raise ValueError(
                "max_explanation_rows must be greater than "
                "or equal to 0"
            )

        if max_chart_rows <= 0:
            raise ValueError(
                "max_chart_rows must be greater than 0"
            )

        if max_categories <= 0:
            raise ValueError(
                "max_categories must be greater than 0"
            )

        self._dataframe = dataframe
        self._dataset_profile = dataset_profile
        self._query_planner = (
            query_planner
            if query_planner is not None
            else QueryPlanner()
        )

        self._max_result_rows = max_result_rows
        self._max_explanation_rows = max_explanation_rows
        self._max_chart_rows = max_chart_rows
        self._max_categories = max_categories

        logger.info(
            "DataAnalystAgent initialized | rows=%d | "
            "columns=%d | max_result_rows=%d",
            len(dataframe),
            len(dataframe.columns),
            max_result_rows,
        )

    @property
    def dataframe(self) -> pd.DataFrame:
        """Return the DataFrame used by this agent."""
        return self._dataframe

    @property
    def dataset_profile(self) -> DatasetProfile:
        """Return the dataset profile used by the agent."""
        return self._dataset_profile

    @property
    def max_result_rows(self) -> int:
        """Return the maximum number of query-result rows."""
        return self._max_result_rows

    def run(
        self,
        question: str,
        generate_explanation: bool = True,
        generate_chart_spec: bool = True,
        chart_type: Optional[str] = None,
    ) -> AgentResult:
        """
        Run the complete data-analysis pipeline.

        Parameters
        ----------
        question:
            Natural-language analytical question.

        generate_explanation:
            Whether to generate an LLM explanation of the result.

        generate_chart_spec:
            Whether to attempt chart generation.

        chart_type:
            Optional explicit chart type:
            bar, line, pie, or scatter.

        Returns
        -------
        AgentResult
            Complete result of the pipeline.

        Raises
        ------
        AgentPlanningError
            If SQL generation fails.

        AgentValidationError
            If generated SQL is rejected by the security layer.

        AgentExecutionError
            If validated SQL cannot be executed.

        AgentExplanationError
            If explanation generation fails.

        AgentChartError
            If chart generation fails.
        """

        if not isinstance(question, str) or not question.strip():
            raise ValueError(
                "question must be a non-empty string"
            )

        question = question.strip()

        logger.info(
            "Starting agent run | question=%s",
            question,
        )

        # ------------------------------------------------------------------
        # 1. Query planning
        # ------------------------------------------------------------------

        try:
            sql = self._query_planner.plan(
                question=question,
                dataset_profile=self._dataset_profile,
            )

        except QueryPlannerError as exc:
            logger.warning(
                "Query planning failed: %s",
                exc,
            )

            raise AgentPlanningError(
                "Could not generate SQL for the question: "
                + str(exc)
            ) from exc

        if not isinstance(sql, str) or not sql.strip():
            logger.warning(
                "Query planner returned an empty SQL statement."
            )

            raise AgentPlanningError(
                "Query planner returned an empty SQL statement."
            )

        sql = sql.strip()

        logger.info(
            "SQL generated successfully | sql=%s",
            sql,
        )

        # ------------------------------------------------------------------
        # 2. SQL executor + security validation
        # ------------------------------------------------------------------

        with SQLExecutor(
            self._dataframe,
            max_result_rows=self._max_result_rows,
        ) as executor:

            # SQLExecutor owns the canonical table name.
            #
            # In production, this is a real string such as "dataset".
            #
            # In tests, SQLExecutor is replaced with a MagicMock. An
            # unconfigured MagicMock.table_name is itself a MagicMock,
            # which is not a valid SQL table identifier.
            #
            # Therefore:
            #   real executor -> use its actual table_name
            #   mock executor -> fall back to DEFAULT_TABLE_NAME
            #
            # DEFAULT_TABLE_NAME is imported from sql_executor.py rather
            # than duplicated here, keeping the table-name contract
            # centralized.
            table_name = getattr(
                executor,
                "table_name",
                DEFAULT_TABLE_NAME,
            )

            if not isinstance(table_name, str) or not table_name.strip():
                table_name = DEFAULT_TABLE_NAME

            validation = validate_sql(
                sql=sql,
                allowed_tables=[table_name],
                max_rows=self._max_result_rows,
            )

            if not validation.is_valid:
                error_messages = []

                for error in validation.errors:
                    detail = (
                        f": {error.detail}"
                        if error.detail
                        else ""
                    )

                    error_messages.append(
                        f"{error.code}: "
                        f"{error.message}"
                        f"{detail}"
                    )

                combined_errors = "; ".join(
                    error_messages
                )

                logger.warning(
                    "Generated SQL rejected by security layer | "
                    "errors=%s",
                    combined_errors,
                )

                raise AgentValidationError(
                    "Generated SQL failed security validation"
                    + (
                        f": {combined_errors}"
                        if combined_errors
                        else "."
                    )
                )

            if not validation.cleaned_sql:
                logger.warning(
                    "SQL security validation succeeded "
                    "but produced no cleaned SQL."
                )

                raise AgentValidationError(
                    "Generated SQL failed security validation: "
                    "SQL security validation succeeded but "
                    "produced no cleaned SQL."
                )

            logger.info(
                "SQL security validation passed | "
                "cleaned_sql=%s",
                validation.cleaned_sql,
            )

            # ----------------------------------------------------------------
            # 3. Execute ONLY validated SQL
            # ----------------------------------------------------------------

            try:
                query_result = executor.execute(
                    validation
                )

            except (
                QueryTimeoutError,
                QueryExecutionError,
                UnvalidatedSQLError,
            ) as exc:

                logger.warning(
                    "SQL execution failed: %s",
                    exc,
                )

                raise AgentExecutionError(
                    "Could not execute the validated SQL query: "
                    + str(exc)
                ) from exc

            if not isinstance(query_result, QueryResult):
                logger.warning(
                    "SQL executor returned an invalid QueryResult."
                )

                raise AgentExecutionError(
                    "Could not execute the validated SQL query: "
                    "SQL executor returned an invalid QueryResult."
                )

            logger.info(
                "SQL execution completed | rows=%d | "
                "truncated=%s",
                query_result.row_count,
                query_result.truncated,
            )

            # ----------------------------------------------------------------
            # 4. Explanation
            # ----------------------------------------------------------------

            explanation: Optional[str] = None

            if generate_explanation:
                try:
                    explanation = explain_query_result(
                        sql=validation.cleaned_sql,
                        query_result=query_result,
                        max_result_rows=(
                            self._max_explanation_rows
                        ),
                    )

                except ExplainerError as exc:
                    logger.warning(
                        "Explanation generation failed: %s",
                        exc,
                    )

                    raise AgentExplanationError(
                        "Could not generate explanation: "
                        + str(exc)
                    ) from exc

                logger.info(
                    "Explanation generated successfully"
                )

            # ----------------------------------------------------------------
            # 5. Chart generation
            # ----------------------------------------------------------------

            chart: Optional[Dict[str, Any]] = None

            if generate_chart_spec:
                try:
                    chart = generate_chart(
                        query_result=query_result,
                        chart_type=chart_type,
                        max_categories=self._max_categories,
                        max_rows=self._max_chart_rows,
                        question=question,
                        sql=validation.cleaned_sql,
                    )

                except (
                    TypeError,
                    KeyError,
                    ValueError,
                ) as exc:

                    logger.warning(
                        "Chart generation failed: %s",
                        exc,
                    )

                    raise AgentChartError(
                        "Could not generate chart specification: "
                        + str(exc)
                    ) from exc

                logger.info(
                    "Chart generation completed | generated=%s",
                    chart is not None,
                )

            # ----------------------------------------------------------------
            # 6. Final result
            # ----------------------------------------------------------------

            result = AgentResult(
                question=question,
                sql=sql,
                validation=validation,
                query_result=query_result,
                explanation=explanation,
                chart=chart,
            )

            logger.info(
                "Agent run completed successfully | "
                "rows=%d | explanation=%s | chart=%s",
                query_result.row_count,
                explanation is not None,
                chart is not None,
            )

            return result


# ---------------------------------------------------------------------------
# Convenience wrapper
# ---------------------------------------------------------------------------


def run_analysis(
    question: str,
    dataframe: pd.DataFrame,
    dataset_profile: DatasetProfile,
    query_planner: Optional[QueryPlanner] = None,
    generate_explanation: bool = True,
    generate_chart_spec: bool = True,
    chart_type: Optional[str] = None,
    max_result_rows: int = DEFAULT_MAX_RESULT_ROWS,
    max_explanation_rows: int = DEFAULT_MAX_EXPLANATION_ROWS,
    max_chart_rows: int = DEFAULT_MAX_CHART_ROWS,
    max_categories: int = DEFAULT_MAX_CATEGORIES,
) -> AgentResult:
    """
    Convenience wrapper around DataAnalystAgent.

    This is useful for the Streamlit/UI layer because it allows the
    complete analysis to be triggered without manually constructing
    the agent object.
    """

    agent = DataAnalystAgent(
        dataframe=dataframe,
        dataset_profile=dataset_profile,
        query_planner=query_planner,
        max_result_rows=max_result_rows,
        max_explanation_rows=max_explanation_rows,
        max_chart_rows=max_chart_rows,
        max_categories=max_categories,
    )

    return agent.run(
        question=question,
        generate_explanation=generate_explanation,
        generate_chart_spec=generate_chart_spec,
        chart_type=chart_type,
    )